.github/workflows/dotnet.yml
=> Fix aritfacts not being uploaded

NwPluginAPI/Core/EffectsManager.cs, NwPluginAPI/Events/EventManager.cs, TemplatePlugin/MainClass.cs
Updated to include the changes made in the Status Effects refactor.
=> Status Effects Update

NwPluginAPI/Events/IEventCancellation.cs
Byte is not enough for port value
Works:
=> Change port parameter to ushort

NwPluginAPI/Core/Respawn.cs, NwPluginAPI/Events/EventManager.cs, TemplatePlugin/EventHandlers.cs, TemplatePlugin/MainClass.cs
=> Update to latest 12.0.0 changes.

Analyzers/NWPluginAPI.Analyzers/Generated/GeneratedEventManager.cs, NwPluginAPI/Core/Player.cs, NwPluginAPI/Core/Respawn.cs, NwPluginAPI/Enums/ServerEventType.cs, NwPluginAPI/Events/EventManager.cs, TemplatePlugin/EventHandlers.cs, TemplatePlugin/MainClass.cs
Added
``Events``
```
WarheadStart
WarheadStop
WarheadDetonation
PlayerMuted
PlayerUnmuted
PlayerCheckReservedSlot
PlayerRemoteAdminCommand
PlayerGameConsoleCommand
ConsoleCommand
TeamRespawnSelected
TeamRespawn
```
``EventManager``
```cs
void RegisterEvents(object plugin, object eventHandler);
```
``Player``
```cs
ItemBase AddItem(ItemType item);
```
Resolved #31
=> Added new few events

NwPluginAPI/Core/Server.cs, NwPluginAPI/Core/Zones/Light/Rooms/LczScp914.cs, NwPluginAPI/Core/Zones/UnknownZone.cs, NwPluginAPI/Events/IEventCancellation.cs, NwPluginAPI/NwPluginAPI.csproj, NwPluginAPI/PluginApiVersion.cs
- Resolves #33.
- Improves PlayerCheckReservedSlot (related to #26 and #34).
- Version bumped to `12.0.0-beta7`.
=> Improved RunCommand and PlayerCheckReservedSlot event, bumped version

NwPluginAPI/Core/Warhead.cs
=> Fixed Warhead.Start and Warhead.DetonationTime

NwPluginAPI.Docs/articles/gettingstarted/codeprerequisites.md, NwPluginAPI.Docs/articles/gettingstarted/gettingstarted-ide.md, NwPluginAPI.Docs/articles/gettingstarted/gettingstarted.md, NwPluginAPI.Docs/articles/intro.md, NwPluginAPI.Docs/articles/toc.md
Some of the docs where a little all over the place. I've condensed the files down to be a little more cohesive and hopefully a lot more helpful.
=> Made docs a little less confusing (Hopefully)

NwPluginAPI/Core/Server.cs
=> FriendlyFire setter fix

Analyzers/NWPluginAPI.Analyzers/Generated/GeneratedEventManager.cs, NwPluginAPI/Core/Player.cs, NwPluginAPI/Core/Server.cs, NwPluginAPI/Enums/ServerEventType.cs, NwPluginAPI/Events/Event.cs, NwPluginAPI/Events/EventManager.cs, NwPluginAPI/Events/IEventCancellation.cs, TemplatePlugin/EventHandlers.cs, TemplatePlugin/Factory/MyPlayer.cs, TemplatePlugin/MainClass.cs
- Changed `IPlayer` to `CommandSender` in `PlayerRemoteAdminCommand` and `PlayerRemoteAdminCommandExecuted` events.
- Added `CommandSender` to `ConsoleCommand` and `ConsoleCommandExecuted` events.
- Introduced `PlayerPreCoinFlip` and `PlayerCoinFlip` events.
- Added Idle Mode methods to `PluginAPI.Core.Server`.
=> Added and improved events, added idle mode

NwPluginAPI/Core/Facility.cs, NwPluginAPI/Core/Map.cs, NwPluginAPI/Core/Player.cs, NwPluginAPI/Core/Round.cs
* Added ``Player.Get(IcommandSender)``
* Added ``Player.Room``
* Added ``Player.Zone``
* Added ``Player.Items`` Resolves #92
* Added ``Player.AddItem(ItemType)``
* Added ``Player.ClearInventory()``
* Re-added ``Facility.TurnOffAllLights()``
* Re-added ``Facility.TurnOnAllLights()``
I really don't know if it would be a re-add because I saw that the code was empty and I thought it was useful, I didn't check if there was ever any code written. 
* Added ``Map.Rooms``
* Added ``Round.Duration``
=> Adding things for Player, Facility, Map, Round

NwPluginAPI/Events/EventManager.cs
=> Fixed UnregisterEvents<T>

NwPluginAPI/Core/Player.cs
Don't worry, I didn't make 1,183 additions and 1,174 deletions.
=> Small stamina addition

Analyzers/NWPluginAPI.Analyzers/Generated/GeneratedEventManager.cs, NwPluginAPI/Enums/ServerEventType.cs, NwPluginAPI/Events/EventManager.cs, TemplatePlugin/EventHandlers.cs, TemplatePlugin/MainClass.cs
* ``GrenadeExploded`` new parameters IPlayer owner, Vector3 position
* ``ItemSpawned`` new parameter Vector3 position
* ``PlaceBlood`` and ``PlaceBulletHole`` new parameters IPlayer player, Vector3 position, Quaternion rotation
* ``PlayerInteractElevator`` new parameter ElevatorChamber elevator
* ``PlayerInteractLocker`` remove parameter byte colliderID replaced for LockerChamber chamber
* ``PlayerInteractShootingTarget`` new parameter ShootingTarget shootingTarget
* ``PlayerReceiveEffect`` new parameter byte intensity and fixed summary in ``ServerEventType.cs ``
* ``PlayerThrowItem`` new parameter ThrowableItem.ProjectileSettings projectileSettings
* ``PlayerThrowProjectile`` remove forceAmount, upwardsFactor, torque, velocity and replaced for ThrowableItem.ProjectileSettings …
=> New Event Parameters and added PlayerInteractGenerator

Analyzers/NWPluginAPI.Analyzers/Generated/GeneratedEventManager.cs, NwPluginAPI/Core/Statistics.cs, NwPluginAPI/Enums/ServerEventType.cs, NwPluginAPI/Events/EventManager.cs, NwPluginAPI/Events/IEventCancellation.cs, TemplatePlugin/EventHandlers.cs, TemplatePlugin/MainClass.cs, TemplatePlugin/TemplatePlugin.csproj
This PR includes #110, #120 and #123.
Resolves #98, #101, #103, #119 and partially #108.
=> Events args update

Analyzers/NWPluginAPI.Analyzers/Generated/GeneratedEventManager.cs, NwPluginAPI/Core/Player.cs, NwPluginAPI/Enums/ServerEventType.cs, NwPluginAPI/Events/EventManager.cs
* Added ``IsSCP`` bool in Player.cs
* Added ``IsWithoutItems`` bool in Player.cs
* Added ``IsOutOfAmmo`` bool in Player.cs
* Added Scp914KnobSetting to  ``Scp914UpgradePickup``, ``Scp914UpgradeInventory``, ``Scp914PickupUpgraded``, ``Scp914InventoryItemUpgraded``
* Added new Event ``Scp914ProcessPlayer`` Execute at the beginning of Scp914Upgrader.Upgrade
* Added new Event ``Scp079CameraChanged``  executed after a SCP-079 changes camera
* Updated the analyzer parameters
* Happy New Year :)
=> Added IsSCP, IsWithoutItems, IsOutOfAmmo bool  and  added a parameter to some SCP914 events

NwPluginAPI/Core/Player.cs
=> Overwatch Fix

NwPluginAPI/Core/Player.cs
Thanks beryl
* This should fix ``collection has been modified`` error when cleaning a player's inventory.
=> Fix ClearInventory

NwPluginAPI/Core/Player.cs
- Added method RemoveItem
- Added method DropItem
- Edited method AddItem
=> Edited Player.cs script

NwPluginAPI/Events/IEventCancellation.cs
=> Events cancellation fix

NwPluginAPI/Core/Server.cs
=> Fix Server.Instance.ReferenceHub being null after a round restart

NwPluginAPI/Core/Player.cs
Originally it was going to be the fix to Issue 153 but I don't plan to waste a branch :trollface:
=> Add Player.Team

NwPluginAPI/Commands/ListCommand.cs, NwPluginAPI/Commands/PluginsCommand.cs, NwPluginAPI/Commands/ReloadCommand.cs, NwPluginAPI/Core/Doors/FacilityDoor.cs, NwPluginAPI/Core/Doors/FacilityGate.cs, NwPluginAPI/Core/Map.cs, NwPluginAPI/Core/Player.cs, NwPluginAPI/Core/PluginHandler.cs, NwPluginAPI/Core/Round.cs, NwPluginAPI/Core/Server.cs
I'm sorry but I'm here to break this number.
* Added ``IsRoundEnded``. Please add ``RoundSummary.singleton.RoundEnded => RoundSummary.singleton._roundEnded``
* Added Name variable
Resolves #169 
* Fixed the NWAPI commands that were not registered.
* Now you can reload the plugins configuration.
* Now you can reload the gameplay configuration.
fix #167 and resolves #166 
* Fixed a bug that ArtificialHealth gave when trying to obtain or change the AHP of a player who is SCP.
* Fixed a bug when trying to use ArtificialHealth since it was being incorrectly invoked.
*  Added  ``Map.Cameras``, ``Map.PocketDimensionTeleports``, ``Map.Lockers``, ``Map.Elevators``, ``Map.TeslaGates``, ``Map.Generators``
* Added ``Map.Broadcast(ushort duration, string message, Broadcast.Flag flag, bool clearPrevius …
=> More changes

NwPluginAPI/Loader/AssemblyLoader.cs
* The fix belongs to Axwabo#2534
=> Fix load priority

NwPluginAPI/Core/Player.cs
=> Add more methods to removeitem

NwPluginAPI/Events/Args/Player/PlayerBannedEvent.cs
=> Resolving issue 203
